# 수치미분
- 입력변수가 미세하게 변할 때 출력변수의 변화값은?
- 미분하려는 함수 구현 -> 극한 개념 구현 -> 분모, 분자 구현

In [1]:
# 입력변수가 하나인 함수의 미분
def numerical_derivate(f,x): #f: 미분하려는 함수, x: 미분 값을 알고자하는 입력값
    delta_x = 1e-4 # lim에 해당되는 작은 값
    return (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)

In [2]:
def my_func1(x):
    return x**2

In [4]:
result = numerical_derivate(my_func1,3)

print('result==',result)

# 함수 f에서 3위에서 값이 미세하게 변한다면 출력값은 6만큼 변화

result== 6.000000000012662


In [7]:
import numpy as np
def my_func2(x):
    return 3*x*(np.exp(x))

In [8]:
result = numerical_derivate(my_func2,2)

print('result==',result)

result== 66.50150507518049


In [11]:
x = np.array([[1,2,3],[4,5,6]])
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
# 입력 변수가 하나 이상인 다변수 함수
# 최종적으로 사용할 미분 함수
def numerical_derivative(f,x): # f: 다변수 함수 / x: 모든 입력변수 (하나 이상의 값의 행렬)
    delta_x = 1e-4
    grad = np.zeros_like(x) # 계산된 수치미분 값을 저장하기 위한 공간 
    print("debug 1. initial input variable =", x)   # 함수의 모든 입력변수 표시
    print("debug 2. initial grad =", grad)          # 초기화값표시
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite']) # numpy의 iterator, 모든 요소를 가리키기 위함
    # 
    while not it.finished: # 변수 개수만큼 반복
        idx = it.multi_index
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx]) # iterator가 가리키고 있는 변수
        
        tmp_val = x[idx] # 원본값이 변하는 경우를 대비하기 위해 원본값 저장
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])   # 현재 차수의 미분 값
        print("debug 5. grad = ", grad)             # 지금까지 미분 값 누적
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [13]:
# 입력변수 1 개인 함수 f(x) = x**2
def func1(input_obj):    
    
    x = input_obj[0]
    
    return  x**2  


# x = 3.0 에서의 편미분 값
numerical_derivative( func1, np.array([3.0]) )

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]


array([6.])

In [14]:
# 입력변수 2 개인 함수 f(x, y) = 2x + 3xy + y^3
def func1(input_obj):    
    
    x = input_obj[0]
    y = input_obj[1] 
    
    return  ( 2*x + 3*x*y + np.power(y,3) )   


# (x,y) = (1.0, 2.0) 에서의 편미분 값
input = np.array([1.0, 2.0]) 

numerical_derivative( func1, input )

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [15]:

# 입력변수 4 개인 함수 
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# input_obj 는 행렬
def func1(input_obj):    
    
    w = input_obj[0, 0]
    x = input_obj[0, 1] 
    y = input_obj[1, 0]
    z = input_obj[1, 1] 
    
    return  ( w*x + x*y*z + 3*w + z*np.power(y,2) )   

# 입력을 2X2 행렬로 구성함
input = np.array([ [1.0, 2.0], [3.0, 4.0] ]) 

numerical_derivative( func1, input )

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])